version: "2.23.3"
services:
#  development:
#    build:
#      context: .
#      dockerfile: dev.Dockerfile
#    working_dir: "/var/application"
#    command: "top -b"
#    ports:
#      - "4000:4000"
#    networks:
#      - primary-network
#    restart: "on-failure"
#    develop:
#      watch:
#        - action: sync
#          path: ./
#          target: /var/application
#          ignore:
#            - node_modules/
  postgresql:
    image: postgres:latest
    ports:
      - "8888:5432"
    restart: "on-failure"
    networks:
      - primary-network
    environment:
      POSTGRES_USER: totp
      POSTGRES_PASSWORD: totp-n00b
      POSTGRES_DATABASE: totp
networks:
  primary-network:
    driver: bridge
