version: "3.8"
services:
  development:
    build:
      context: .
      dockerfile: dev.Dockerfile
    working_dir: "/var/application"
    volumes:
      - ".:/var/application"
    command: "npm run dev"
    ports:
      - "4000:4000"
    networks:
      - primary-network
    restart: "on-failure"
  postgresql:
    image: postgres:latest
    ports:
      - "8888:5432"
    restart: "on-failure"
    networks:
      - primary-network
    environment:
      POSTGRES_USER: totp
      POSTGRES_PASSWORD: totp-n00b
      POSTGRES_DATABASE: totp
networks:
  primary-network:
    driver: bridge
